export const METRIC_POINTS = {
  VALIDATION_FAIL_TOTAL: 'csrf.validation.fail.total',
  VALIDATION_FAIL_BY_REASON: 'csrf.validation.fail.by_reason',
  VALIDATION_FAIL_DURATION: 'csrf.validation.fail.duration',
  VALIDATION_SUCCESS_TOTAL: 'csrf.validation.success.total',
  VALIDATION_SUCCESS_DURATION: 'csrf.validation.success.duration',
  VALIDATION_DURATION: 'csrf.validation.duration',
  TOKEN_GENERATION_TOTAL: 'csrf.token.generation.total',
  TOKEN_GENERATION_DURATION: 'csrf.token.generation.duration',
  ONESHOT_GENERATION_TOTAL: 'csrf.one_shot.generation.total',
  ONESHOT_GENERATION_DURATION: 'csrf.one_shot.generation.duration',
  ORIGIN_MISMATCH_TOTAL: 'csrf.origin.mismatch.total',
  FETCH_METADATA_CROSS_SITE_BLOCKED: 'csrf.fetch_metadata.cross_site.blocked',
  FETCH_METADATA_MISSING: 'csrf.fetch_metadata.missing',
  CONTEXT_BINDING_FAIL_TOTAL: 'csrf.context.binding.fail.total',
  ONESHOT_REPLAY_ATTEMPT_TOTAL: 'csrf.one_shot.replay_attempt.total',
  ONESHOT_ACTION_MISMATCH: 'csrf.one_shot.action_mismatch',
  NONCE_CACHE_HIT_RATE: 'csrf.nonce_cache.hit_rate',
  KEY_ROTATION_EVENTS: 'csrf.key.rotation.events',
  KEY_ROTATION_FAILURES: 'csrf.key.rotation.failures',
  CRYPTO_FAILURES: 'csrf.crypto.failures',
  ANOMALY_DUPLICATE_TOKEN: 'csrf.anomaly.duplicate_token',
  ANOMALY_MULTIPLE_SOURCES: 'csrf.anomaly.multiple_sources',
  ANOMALY_TOKEN_LENGTH: 'csrf.anomaly.token_length_anomaly',
  ANOMALY_TIMING_VARIANCE: 'csrf.anomaly.timing_variance',
  ANOMALY_VALIDATION_SPIKE: 'csrf.anomaly.validation_spike',
  ANOMALY_FAILURE_SPIKE: 'csrf.anomaly.failure_spike',
  ANOMALY_GENERATION_SPIKE: 'csrf.anomaly.generation_spike',
} as const

export type MetricPoint = (typeof METRIC_POINTS)[keyof typeof METRIC_POINTS]
